---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: maven:3.8.3-openjdk-17
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
    commands:
      - mvn -s ./accruals_settings.xml clean verify

  - name: sonar
    image: maven:3.8.3-openjdk-17
    depends_on:
      - build
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
      SONAR_HOST:
        from_secret: sonar_cloud_host
      SONAR_TOKEN:
        from_secret: sonar_cloud_token
    commands:
      - mvn -s ./accruals_settings.xml sonar:sonar 
        -Dsonar.host.url=$${SONAR_HOST}
        -Dsonar.login=$${SONAR_TOKEN}
        -Dsonar.organization=ukhomeoffice
        -Dsonar.projectKey=callisto-accruals-restapi
        -Dsonar.branch.name=$DRONE_BRANCH
        -Dsonar.projectName=callisto-accruals-restapi -Dsonar.qualitygate.wait=true
        -Dsonar.exclusions=src/main/java/uk/gov/homeoffice/digital/sas/accruals/CallistoAccrualsRestapiApplication.java
    when:
      event:
        exclude:
          - pull_request

  - name: lint_dockerfile
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile

  - name: build_tag_push_ecr
    pull: if-not-exists
    image: plugins/ecr
    depends_on:
      - sonar
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: ecr_accruals_restapi_access_key_id
      secret_key:
        from_secret: ecr_accruals_restapi_secret_access_key
      repo: callisto/accruals-restapi
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-accruals-restapi

trigger:
  status: success

steps:
  - name: lint_helm_files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_file: ./helm/values.yaml

  - name: deploy_to_dev
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=${DRONE_COMMIT_SHA}
      values_file: ./helm/values.yaml
      release: callisto-accruals-restapi
      kube_certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyRENDQWNDZ0F3SUJBZ0lSQUxBdk1yVGVzQkhNUkliR0ZZa3JsaHN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4TnpBNE1qZ3hPVFU0TlRSYUZ3MHlOekE0TWpneApPVFU0TlRSYU1CVXhFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURQNm5ZVGpmbmR2T2kxOEltYm5idk9aOXJ3c1hxSkZFTE1IVTkxT2VIaXFIT2kKT1luVFZ3cmpCaDJpZExUM0ozbkVoYnM0WFRIcVlwcVEzdmcwVzluVVRPMnk5ZmFmdlRZVTk0NGZXUTl1SXJOZwo1Y0Q0SXhzK05vWTJmdkkrcStYUUM2SFNiRGJ0S0dOUy9Kbmc5SFdsazF2dzY0TlBwbU5IMTJtUFVvNGpGZnc5CmZoL3RwY1k5akVsZnhJckJBVEJzNHhYcDJHOFFrK1ZCSWE5bnF4bmtVTHJvT0t2Y092T3g4RDU1TXdXcEVKc3QKdENZSXFHM05xdlhMcUdTQzdueHoxYmJNSmZjRDdBRmdvZnM1bXZ0bmlRTHBnZG93WmxNc3g2cnJVM2pBUkw3OApvTktXR3p3c3BKNjhybXdhSGZ4NlRBWldHbUxSU2NPd0xlbWJ3cDRIQWdNQkFBR2pJekFoTUE0R0ExVWREd0VCCi93UUVBd0lCQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDb2RrZkMKS2NOYzY5cXR6ZllWUUFlajFVb0hhMjhUUzlqMHV3RVdqWlU0dFVWR2cvZDNCK2YvcnYyN2tqRGM3U2JJSForVQpxMlpMVlVnYU85OVoyUjQyUFhNVTZCRUVUdjUvT0t4amdkNlFNQnFFVkxBdU1XZFpsbnBkMEpDMDFGd0tJb3BGCnVpVUFoWnRjR0tJRXg1U1N1SUlKdFU4a2pnR2xuS0V6aXJrUVVCOUJUOURSQ1VhelQ1ZUp6VFVLSVliWjBNL3gKSUZMbUQvZmZZeFhmRGlSM25YWkdZSWpkUGJHYW42ZU5pZExjQkdEZkxabzZFdkJTR2FUSHl5KzEyc3c2clhTVwpBTVFWd3BUY2ZpSlM1NG9xSXhDU3dyam5XNFZYRnhiSC96SWZXMGs5M29ucERNdXhjT20rN0NuZjViRlJEdlpzCjRCaEV1ank1eEVtajA1TWwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      kube_api_server:
        from_secret: dev_kube_api_url
      kube_token:
        from_secret: dev_kube_token
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - callisto-accruals-restapi
  - callisto-accruals-restapi-deploy

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          <${DRONE_BUILD_LINK}|Build #{{build.number}}> succeeded! :tada:
        {{else}}
          <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :broken_heart:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <https://sonarcloud.io/dashboard?id=callisto-ui&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>

---
kind: pipeline
type: kubernetes
name: urgent notifications

trigger:
  status:
    - failure

depends_on:
  - callisto-accruals-restapi
  - callisto-accruals-restapi-deploy

slack: &slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_urgent_webhook_url
    channel: callisto-urgent-tech-notifications
    username: Drone

steps:
  - name: slack_build_urgent
    <<: *slack
    settings:
      template: |
        <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :this-is-fine-fire:
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Author: {{ build.author }}
#    when:
#      branch:
#        - main
