---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean package