---
kind: pipeline
type: kubernetes
name: lint-files

platform:
  os: linux
  arch: amd64

trigger:
  event:
    exclude:
      - promote

steps:
  - name: lint_dockerfile
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile

  - name: lint_helm_files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_file: ./helm/values.yaml

---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

accruals_quay_settings: &accruals_quay_settings
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/callisto-accruals-restapi
    username:
      from_secret: quay_robot_name
    password:
      from_secret: quay_robot_token
    file: Dockerfile

steps:
  - name: build
    image: maven:3.8.3-openjdk-17
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
    commands:
      - mvn -s ./accruals_settings.xml clean verify

  - name: sonar
    image: maven:3.8.3-openjdk-17
    depends_on:
      - build
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
      SONAR_HOST:
        from_secret: sonar_cloud_host
      SONAR_TOKEN:
        from_secret: sonar_cloud_token
    commands:
      - mvn -s ./accruals_settings.xml sonar:sonar
        -Dsonar.host.url=$${SONAR_HOST}
        -Dsonar.login=$${SONAR_TOKEN}
        -Dsonar.organization=ukhomeoffice
        -Dsonar.projectKey=callisto-accruals-restapi
        -Dsonar.branch.name=$DRONE_BRANCH
        -Dsonar.projectName=callisto-accruals-restapi -Dsonar.qualitygate.wait=true
        -Dsonar.exclusions=src/main/java/uk/gov/homeoffice/digital/sas/accruals/CallistoAccrualsRestapiApplication.java
    when:
      event:
        exclude:
          - pull_request

  - name: build_tag_push_quay_branch
    <<: *accruals_quay_settings
    depends_on:
      - build
    settings:
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_SOURCE_BRANCH%%/*}
    when:
      event:
        - pull_request

  - name: build_tag_push_quay
    <<: *accruals_quay_settings
    depends_on:
      - sonar
    settings:
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi-branch-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-accruals-restapi

trigger:
  event:
    - pull_request

steps:
  - name: branch_deploy
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=${DRONE_COMMIT_SHA}
        - branch=${DRONE_SOURCE_BRANCH%%/*}
      values_file: ./helm/values.yaml
      release: callisto-accruals-restapi-${DRONE_SOURCE_BRANCH%%/*}
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
          from_secret: notprod_kube_api_url
      kube_token:
        from_secret: notprod_kube_token

---
kind: pipeline
type: kubernetes
name: callisto-accruals-restapi-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files
  - callisto-accruals-restapi

trigger:
  status: success

steps:
  - name: deploy_to_dev
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=${DRONE_COMMIT_SHA}
      values_file: ./helm/values.yaml
      release: callisto-accruals-restapi
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: notprod_kube_api_url
      kube_token:
        from_secret: notprod_kube_token
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push
    exclude:
      - pull_request

depends_on:
  - callisto-accruals-restapi
  - callisto-accruals-restapi-deploy

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          <${DRONE_BUILD_LINK}|Build #{{build.number}}> succeeded! :tada:
        {{else}}
          <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :broken_heart:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <https://sonarcloud.io/dashboard?id=callisto-ui&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>

---
kind: pipeline
type: kubernetes
name: urgent notifications

trigger:
  status:
    - failure
  event:
    exclude:
      - pull_request

depends_on:
  - callisto-accruals-restapi
  - callisto-accruals-restapi-deploy

slack: &slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_urgent_webhook_url
    channel: callisto-urgent-tech-notifications
    username: Drone

steps:
  - name: slack_build_urgent
    <<: *slack
    settings:
      template: |
        <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :this-is-fine-fire:
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Author: {{ build.author }}
    when:
      branch:
        - main
