---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: accruals-restapi
          image: accruals
          imagePullPolicy: Never
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 8080
      initContainers:
        - name: accruals-kafka-tls
          image: accruals
          imagePullPolicy: Never
          env: {{ toYaml .Values.env.kafka | nindent12 }}
          command: ["/helm/scripts/kafkaCerts.sh $(AWS_ACCESS_KEY) $AWS_SECRET_KEY $(CERTIFICATE_AUTHORITY_ARN) $(CERTIFICATE_ARN) $(ACCRUALS_KEY $(PASSWORD)"]
          volumeMounts:
          - name: kafka
            mountPath: "/tmp"
      volumes:
      - name: kafka
        emptyDir: {}

