---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: accruals-restapi
          image: accruals:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 8080
      initContainers:
        - name: accruals-certification
          image: accruals:latest
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.kafka | nindent 12}}
          command:
              ['sh', '-c', "keytool -importkeystore -srckeystore $(KEY_PAIR) -destkeystore kafka.client.keystore.jks -srcstoretype pkcs12 -alias shared -storepass $(PASSWORD) -keypass $(PASSWORD) -srcstorepass $(PASSWORD)"]
