{{- if ne .Values.branch "main" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
    cert-manager.io/solver: route53
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-origin: "https://*.dev.callisto-notprod.homeoffice.gov.uk"
spec:
  tls:
    - hosts:
        - {{ .Values.branch }}-accruals.dev.callisto-notprod.homeoffice.gov.uk
      secretName: callisto-accruals-tls-{{ .Values.branch }}
  rules:
    - host: {{ .Values.branch }}-accruals.dev.callisto-notprod.homeoffice.gov.uk
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Release.Name }}
                  port:
                    number: 8080
{{ end }}