mainContainerImage:
  repositoryName: callisto-accruals-restapi
  tag: latest # overwritten by deployments

databaseMigrationImage:
  repositoryName: callisto-accruals-database
  tag: latest # overwritten by deployments

db:
  secretKeyRefName: callistodev-rds
  schemaName: accruals

service:
  containerPort: 9090

ingress:
  branch: main # overwritten by branch deploy
  host: accruals.dev.callisto-notprod.homeoffice.gov.uk
  tlsSecretName: callisto-accruals-tls
  corsOrigin: "https://*.dev.callisto-notprod.homeoffice.gov.uk"