mainContainerImage:
  repositoryName: callisto-accruals-restapi
  tag: latest # overwritten by deployments

databaseMigrationImage:
  repositoryName: callisto-accruals-database
  tag: latest # overwritten by deployments

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

db:
  secretKeyRefName: callisto-test-aurora
  schemaName: accruals

service:
  containerPort: 9090