-- =============================================================================
-- Description: Returns list of Accruals impacted by Time Entry. Covering dates:
--              FROM the earliest impacted accrual or Time Entry start date, whichever is earliest,
--              minus one day ('day before' used in calculation of cumulative totals)
--              UNTIL the end of agreement corresponding to the latest impacted accrual or Time
--              Entry end date, whichever is latest.
--
-- Parameters:
-- @p_tenant_id             - Tenant ID
-- @p_person_id             - Person ID generated by Person container
-- @p_time_entry_id         - Time Entry ID generated by Timecard container
-- @p_time_entry_start_date - Time Entry start date (it can be before the first found contribution)
-- @p_time_entry_end_date   - Time Entry end date (it can be after the last found contribution)
--
-- Returns: Set of Accrual table records meeting the input criteria
-- =============================================================================

CREATE OR REPLACE FUNCTION accruals.get_impacted_accruals(
    p_tenant_id VARCHAR, p_person_id VARCHAR,
    p_time_entry_id VARCHAR, p_time_entry_start_date DATE, p_time_entry_end_date DATE)
    RETURNS SETOF accruals.accrual
    LANGUAGE plpgsql
AS'
    DECLARE
        v_min_date DATE;
        v_max_date DATE;
        v_agreement_end_date DATE;
    BEGIN
        -- for the input Time Entry ID, get the earliest between Time Entry start date and earliest
        -- contribution date, and the latest between Time Entry end date and latest contribution date
        SELECT LEAST(MIN(ac.accrual_date), p_time_entry_start_date),
               GREATEST(MAX(ac.accrual_date), p_time_entry_end_date)
        INTO v_min_date, v_max_date
        FROM accruals.accrual AS ac
        WHERE (ac.contributions -> ''timeEntries'') ? p_time_entry_id;

        SELECT ag.end_date
        INTO v_agreement_end_date
        FROM accruals.agreement AS ag
        WHERE ag.tenant_id = p_tenant_id
        AND ag.person_id = p_person_id
        AND v_max_date
                BETWEEN ag.start_date AND v_agreement_end_date;

        RETURN QUERY
            SELECT ac.*
            FROM accruals.accrual ac
            WHERE ac.person_id = p_person_id
              AND ac.tenant_id = p_tenant_id
              AND ac.accrual_date
                BETWEEN v_min_date - 1 AND v_agreement_end_date
            ORDER BY ac.accrual_date;
    END;';
