@startuml

entity accrual {
  * id : number <<PK>>
  --
  * type_id : number <<FK>>
  --
  * balance : number
  * day : date
}

entity contribution {
  * id : number <<PK>>
  --
  * time_entry_id : number <<FK>>
  * accrual_id : number <<FK>>
  --
  * value : number
}

entity accrual_type {
  * id : number <<PK>>
  --
  * name : string
  * measurement_unit : enumeration
}
accrual ||.. accrual_type
contribution ||.. accrual

@enduml
